### PR TITLE
Enable data-score-name by passing data() to extend

### PR DESCRIPTION
**Pull request by troyharvey**
See http://www.wbotelhos.com/raty#comment-678

### CODE REVIEW

**Comment by troyharvey** [comment]
Nice! Thanks @maxicms. :+1: :-1: @wbotelhos?

**Comment by wbotelhos** [comment]
Could you create a spec for that?

**Comment by arturmamedov** [comment]
This little change enable the jquery data API for raty .... WOW! Amazing! +1

**Comment by wbotelhos** [comment]
Raty works with data attribute a long time ago, but as a whitelist @arturmamedov: https://github.com/wbotelhos/raty/blob/master/lib/jquery.raty.js#L62

This commit just apply all data as option. I don't know if it is a good idea we have all data attributes cached on plugin.

**Comment by arturmamedov** [comment]
@wbotelhos oh great, i remember something from doc, but today your website was down :(

And can we extend whitelist, in example i need to change the style of star-on, star-off etc.

What problems might arise if we set (all or more) options from the data attributes?

**Comment by arturmamedov** [comment]
Nothing new on this? I vote up this thing, its very usefull!

**Comment by wbotelhos** [comment]
The problem with all that is the Fat DOM. By the way, this code has no test.

**Comment by arturmamedov** [comment]
If i say +1 again :D ?

**Comment by wbotelhos** [comment]
Hi, @arturmamedov , the problem is this code has no test. Me or someone else must to do that. ;)

**Pull request closed without merging**
