### PR TITLE
Added other assets to bower main files and included bower.json in package

### PR DESCRIPTION
**Pull request by juriejan**
I've added the css, fonts and images to the main bower package files and included the `bower.json` file in the package. This would allow us to make use of tools that automatically hookup assets from Bower packages. (I'm currently using [main-bower-files](https://github.com/ck86/main-bower-files))

### CODE REVIEW

**Comment by Darex1991** [comment]
:+1:

Worked for me with:

    bower install juriejan/raty --save

**Comment by wbotelhos** [comment]
Hi @juriejan ,

Could you rebase it?

**Comment by juriejan** [comment]
Done @wbotelhos!

**Comment by wbotelhos** [comment]
Thank you @juriejan ! :)

**Comment by juriejan** [comment]
Not sure I understand the question @wbotelhos. I guess you can just attach it to any version you choose.

**Comment by wbotelhos** [comment]
I don't know if Bower need a tagged version to work or if it works just being on the master branch.

**Comment by juriejan** [comment]
I'm also not sure. Haven't used Bower for a while.

**Pull request merged**
